#------------------------------------------------------------------------------
# Loads the values of important JOBRUNNER system environment variables into the
# current job.  Here's the list of variables loaded:
# 
#   NF_BUILD
#   NF_CACHE
#   NF_CODEDOC
#   NF_REPOS
#   NF_ROOT
#   NF_SAMPLES_CADENCE
#   NF_SNIPPETS
#   NF_TEMP
#   NF_TEST
#   NF_TOOLBIN
# 
#   NC_ACTIONS_ROOT
#   NC_BUILD
#   NC_CACHE
#   NC_NUGET_DEVFEED
#   NC_NUGET_VERSIONER
#   NC_REPOS
#   NC_ROOT
#   NC_TEMP
#   NC_TEST
#   NC_TOOLBIN

name: neon-environment
description: Loads important JOBRUNNER system environment variables into the current job.
inputs:
  branch:
    description: Optionally specifies the branch or tag (defaults to "master")
    required: false
    default: master
runs:
  using: composite
  steps:
  - shell: pwsh
    run: |
      
      # Loads a user or system environment variable into the current job process.
      function LoadVariable()
      {
          [CmdletBinding()]
          param (
              [Parameter(Position=0, Mandatory=1)]
              [string]$variable
          )
          
          # Try the USER variables first

          if (($item = $(Get-ItemProperty -Path "HKCU:\Environment" -Name $variable -ErrorAction SilentlyContinue)))
          {
              [System.Environment]::SetEnvironmentVariable($variable, $item.$variable)
              return
          }
          
          # Fall-back to the system variables
          
          if (($item = $(Get-ItemProperty -Path "HKEY_LOCAL_MACHINE\SYSTEM\CurrentControlSet\Control\Session Manager\Environment" -Name $variable -ErrorAction SilentlyContinue)))
          {
              [System.Environment]::SetEnvironmentVariable($variable, $item.$variable)
              return
          }
          else
          {
              throw "The [$variable] environment variable does not exist."
          }
      }

      LoadVariable NF_BUILD
      LoadVariable NF_CACHE
      LoadVariable NF_CODEDOC
      LoadVariable NF_REPOS
      LoadVariable NF_ROOT
      LoadVariable NF_SAMPLES_CADENCE
      LoadVariable NF_SNIPPETS
      LoadVariable NF_TEMP
      LoadVariable NF_TEST
      LoadVariable NF_TOOLBIN
 
      LoadVariable NC_ACTIONS_ROOT
      LoadVariable NC_BUILD
      LoadVariable NC_CACHE
      LoadVariable NC_NUGET_DEVFEED
      LoadVariable NC_NUGET_VERSIONER
      LoadVariable NC_REPOS
      LoadVariable NC_ROOT
      LoadVariable NC_TEMP
      LoadVariable NC_TEST
      LoadVariable NC_TOOLBIN
